# Generated by Django 3.1.3 on 2020-12-16 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('profile_image', models.URLField(max_length=300)),
                ('bio', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoogle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=100)),
                ('google_sub', models.CharField(max_length=255, unique=True)),
                ('email_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.emailaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=100)),
                ('facebook_id', models.CharField(max_length=100, unique=True)),
                ('email_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.emailaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(null=True)),
                ('valid', models.BooleanField(default=True)),
                ('is_email_token', models.BooleanField(default=False)),
                ('token', models.CharField(default=user.models.generate_token, max_length=12, unique=True)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auths', to='user.emailaddress')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['user', 'primary'], name='user_emaila_user_id_f7e3f2_idx'),
        ),
    ]
