# Generated by Django 3.1.3 on 2020-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20201216_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='subtitle',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='storytag',
            unique_together={('story', 'tag')},
        ),
    ]
