# Generated by Django 3.1 on 2020-12-25 20:02

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20201223_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='uid',
            field=models.CharField(default=story.models.generate_uid, max_length=100, unique=True),
        ),
    ]
