# Generated by Django 3.1 on 2020-12-30 17:54

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20201230_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.JSONField(default=story.models.default_body),
        ),
    ]
