# Generated by Django 3.1 on 2021-01-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20201230_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='story',
            name='featured_image',
            field=models.URLField(blank=True),
        ),
    ]
