# Generated by Django 3.1.3 on 2021-01-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20210101_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='main_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='trending_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
