# Generated by Django 3.1 on 2020-12-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20201231_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='featured_image',
            field=models.URLField(blank=True),
        ),
    ]
